spring.application.name=DatabaseProjectDemo

# Common Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Activate a Profile (dev or uat)
spring.profiles.active=uat

# UAT Profile (production database)
spring.config.activate.on-profile=uat
spring.datasource.url=jdbc:postgresql://localhost:5432/production
spring.datasource.username=<uat_username>
spring.datasource.password=<uat_password>
spring.jpa.hibernate.ddl-auto=validate
