# --- Bootstrap superuser ---
app.bootstrap-superuser.email=${APP_BOOTSTRAP_EMAIL}
app.bootstrap-superuser.password=${APP_BOOTSTRAP_PASSWORD}
app.bootstrap-superuser.first-name=${APP_BOOTSTRAP_FIRST_NAME}
app.bootstrap-superuser.last-name=${APP_BOOTSTRAP_LAST_NAME}

# --- Database ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# --- Server ---
server.port=8080
server.address=0.0.0.0

app.default-user-password=${APP_DEFAULT_USER_PASSWORD}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:k8s}
