spring.datasource.url=jdbc:postgresql://localhost:5432/registration
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none

app.bootstrap-superuser.email=bootstrap@system.local
app.bootstrap-superuser.password=ChangeMe123!
app.default-user-password=UserDefault123!

