spring.application.name=DatabaseProjectDemo

# Common Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Activate a Profile (dev or uat)
spring.profiles.active=uat

# UAT Profile (production database)
spring.config.activate.on-profile=uat
spring.datasource.url=jdbc:postgresql://localhost:5432/production
spring.datasource.username=<uat_username>
spring.datasource.password=<uat_password>


# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
