app.bootstrap-superuser.email=bootstrap@system.local
app.bootstrap-superuser.password=bootstrap123
app.bootstrap-superuser.first-name=System
app.bootstrap-superuser.last-name=Bootstrap
server.address=0.0.0.0
