spring.application.name=DatabaseProjectDemo

# Common Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Activate a Profile (dev or uat)
spring.profiles.active=dev

# Development Profile (staging database)
spring.config.activate.on-profile=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/staging
spring.datasource.username=<dev_username>
spring.datasource.password=<dev_password>
spring.jpa.hibernate.ddl-auto=update
