apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: omutwar
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  APP_BOOTSTRAP_PASSWORD: "bootstrap123"
